### ISSUE TITLE
Integrate material design into uw-frame

### ISSUE THREAD

**Issue by timlevett** [UW-Madison-DoIT/uw-frame#151]
https://material.angularjs.org/latest/

https://www.google.com/design/spec/material-design/introduction.html

**Comment by smargovsky** [comment]
Ok, I want to learn : why is Angular Material better than Bootstrap UI?  What exactly do we gain from this move - i.e. why isn't it a lateral move but an improvement?

Not the ideas behind Material Design, but the actual code / framework.  1,400 + issues currently on Angular Material.  

Why not [Angular Materialize](http://krescruz.github.io/angular-materialize/)?

Thanks.

**Comment by timlevett** [comment]
I'm not sure why the sudden change in heart @smargovsky. When we initially brought up material we didn't get any kick back from anyone, but now that its becoming more real there is only doubt coming from you. Everyone else seems to be on board.  That being said, we haven't finalized what framework/implementation of material design and would be happy to discuss options. Lets work together to make a better product.

**Comment by timlevett** [comment]
Looking at Angular Materialize, they also have about 600 open issues. It does look neat though, curious how supported that product is. Since its an individual hosting it and all. We originally liked the material implementation that came from the angular team, well, because its from the angular team backed by Google. 

We get a lot more directives out of Angular Material than we get from Bootstrap UI. A lot more UX thought out designs. Bootstrap seems to give you a bunch of tools, and leave it to your team to figure out the deliverable. This leaves it to a UW UX team to come up with design patterns, a lot of them. We just don't have the bandwidth to keep up with that. It doesn't scale well on our budget. So we thought that it could help to start with a more in-depth, thought out UI design. Enter Material. We all agree that the implementation from material doesn't have everything, but it has quite a bit.

I would also ask you @smargovsky, what would you prefer? Do you strongly enjoy bootstrap? Would you rather go of the way of foundation?

**Comment by timlevett** [comment]
I also kind of liked the answer that this person put on stackoverflow: http://stackoverflow.com/questions/27438336/choosing-bootstrap-vs-material-design

We could use both?

**Comment by smargovsky** [comment]
@timlevett, I have no preference.  

I think Material Design ( :tm: Google ) is a great resource for designers and developers.  I am not thrilled about the rigidity of the specs it provides, nor am I convinced that a web app benefits wholly from looking like a native Android app.  Further, Angular Material is but a simple implementation of the design specs - with all of the problems and issues of any implementation.

That said, I am also not fully happy with Bootstrap ( ah, first world developer problems! ).  It is a great starter but leaves a lot of necessary customization and implementation of design patterns.  I do like where Foundation has gone recently, though Bootstrap 4 will all but erase the differences ( again ).  I am also pleasantly surprised by how well-built Bootstrap UI actually is, and how quickly they fix issues ( akin to how fast you guys work on UW-Frame ).

The reason for my asking this question is because I do not share your optimism that a front end framework ( a bunch of CSS and JS ) will relieve your team ( or ours for that matter ) from having to come up with design patterns.  As stated, we are not creating a native Android app ( which is what Material Design as a theory was built for ).  Implementing design patterns and best practices from Material Design is possible with any front end framework, especially because most of our use cases are special snowflakes ( at least for our team ).  I am lost on the utility that is provided by switching to Angular Material.  I was hoping for solid, concrete examples of where we would all benefit from such a switch - justification for the time spent ( 2+ months? ) re-designing and re-implementing MyUW and the apps we already have.

Example :

[Swipe Down](https://material.angularjs.org/latest/api/directive/mdSwipeDown) has no equivalent built into Bootstrap nor Bootstrap UI.  You would need to use ngTouch and write custom behavior using the $swipe service.

Other real world ( objective ) examples?

**Conversation intensifies**

**Comment by timlevett** [comment]
Thanks for the response. We really appreciate the feedback. We do have some concrete examples of things we would like to use from angular material that would benefit the uw-frame project specifically. This is not a complete list, but its a start. Please feel free to add anything.

* Sidebar. The md's sidebar is just really well done, and we need one on mobile. We just had a story this sprint where we had spent a lot of time on the micro interactions of the menu. Lotta dev time sunk into it.
* md-titlebar. The bootstrap nav is challenging for us to work with so we have had to write a lot of custom code to get it to function properly. Playing around with the titlebar in angular material it seemed pretty straight forward.
* circle buttons : more generally the buttons. We currently have custom ones, we want non-custom ones. Circle button is currently a directive, md has these.
* Dynamic theming: You can do dynamic theming in md with custom pallets. This will be amazing for system skins.
* Flex grid : Right now we are using bootstrap grid which is okay, however we had to inject a custom drag/drop thing written with jquery to get drag/drop to work. With the flex grid system and a plugin designed to be used with angular and material flex directives we can have drag/drop w/o jquery present. That feature seemed pretty polished
* Cards : We are looking to replace our custom card styling with the md-card directive. 
* toast : We desperately need a toast mechanic that isn't too intrusive to a user when they do a change. e.g.: you just deleted that app from your favs, did you mean to? click here to undo.

We have had thoughts of having both md and bootstrap (they are compatible). That could be a way to have the opportunity to use both. An easier transition if you will.

**Comment by smargovsky** [comment]
_starting flame war_

Sidebar is a great design pattern that has been implemented in most frameworks ( [Bootstrap 4 example](http://v4-alpha.getbootstrap.com/examples/offcanvas/) ). And I can't find md-titlebar anywhere.

Circle buttons != FAB because that breaks the Material Design specs.

[Angular Material Dynamic Theming](https://material.angularjs.org/latest/Theming/05_under_the_hood) - does this seem smart / efficient / fast for a large app?  Inspect that page's head section!

Flex / cards are first class citizens in Bootstrap 4.  ngToast seems like a good toast solution.

_ending flame war_

**Comment by timlevett** [comment]
I appreciate your opinion. I wholeheartedly agree, there is more than one way to do most of these things. 

The toolbar is https://material.angularjs.org/latest/demo/toolbar. Sorry, miss remembered the name of it. Toolbar not titlebar. Thanks for the info on the FAB, I'll have to check that out. There is a design pattern to have an icon surrounded by circle that is an action item that isn't floating as well. I agree, multiple floating icons on a page is against spec.

We have a current theming solution in place that is vary similar to what they have presented. Curious if that implementation has changed because I don't have a bunch of injected elements in <head> with another app I wrote using material that has multiple themes.

I'm happy cards are making there way to bootstrap 4, I really like the card model. So is that saying you would rather move to bootstrap 4 than angular material? I have looked at ngToast before, seems decent, I agree!

**Comment by vertein** [comment]
Sorry, late to the party, but here I go.

I like a complete solution that not only thinks out components, but also, language, text, animations, layouts, interactions, etc.  I believe that this will give us a standard to base working off and then customization if we don't have the design provided.  I think it will save time.  Right now, we've created some new components (our cards, our menu, our app-header) , instead we would try solve our problems using an already thought of design.

I've only read and played with Material Design, so I'll checkout out the other suggestions as well.  I do believe that others have tried to figure things already, like I assume cards, side menu, headers are not a thing unique to Material.

The reason I dug into Material first is admittedly the google angular - google material connection and that I have an Android phone.  I would think that angular material would just work with our product and be super cool.  I do think whatever route we go down, will change our look and feel of our web-app (probably for the better).  I'm going to take a look at Bootstrap 4 and see what that's all about too.

**Comment by smargovsky** [comment]
@keirserrie and company, I've been wondering : Material Design is made for mobile / Android and functions great on that medium.  However, are the same UX patterns appropriate for web?  

Example : tables.  
[Material Design Data Tables](https://www.google.com/design/spec/components/data-tables.html) appear to be defined as well as the rest of the components but are lacking in [Angular Material](https://github.com/angular/material/search?q=table&utf8=%E2%9C%93).  Do we have to re-implement the wheel when we move to Material Design ( for the deliverable css / js )?

**Comment by smargovsky** [comment]
This space is taking off : http://www.lightningdesignsystem.com/ and http://www.ibm.com/design/language/framework/experience

**Comment by timlevett** [comment]
Done
