### ISSUE TITLE
Namespace Issues

### ISSUE THREAD

**Issue by bhill6** [UW-Madison-DoIT/uw-frame#30]
I'm porting a stand alone angular-based application to live in the uw-frame and had previously made the unfortunate choice to name one of the controllers 'SearchController'.  

I eventually realized that the uw-frame angular app already registered a controller constructor named 'SearchController', and in this case, the uw-frame's version was clobbering mine, since it happened to register after my version. I solved my problem by simply registering it under a different name.

To avoid confusion, I would suggest registering all of the built-in uw-frame components with a common prefix, such as 'Portal', including controllers, service, directives and filters, since any of them could be candidates for namespace collisions. Angular constructor functions (and their names) get put in the same application-global bucket for that type of component, even across angular modules.

To be clear, this isn't about module names or RequireJS issues, but the name that is used when a component constructor is registered with angular, like this:

```javascript
angular.module('portal.search.controllers').controller('SearchController',['blah',function(blah) { 
}]);
```
This would be better:
```javascript
angular.module('portal.search.controllers').controller('PortalSearchController',['blah',function(blah) { 
}]);
```
Without a prefixing scheme of some kind, this issue will probably keep coming up as both the uw-frame and frame apps evolve over time.

If I missed some other way to avoid this problem, feel free to to enlighten me about it. :)

**Comment by timlevett** [comment]
Great suggestion! We will look into this.

**Comment by paulerickson** [comment]
:+1: 

If your Controller belongs to a route, then you can avoid this by passing the Controller object itself, instead of registering the it to a name and passing the name.

[Here](https://bitbucket.org/uwmadison_doit/bucky-backup/src/e012e978496c/bucky-backup-war/src/main/webapp/my-app/report/?at=master) is a simple example of what I mean.
Notice that only module.js has an angular dependency, and both route.js and controller.js have an `$inject` property set -- this is how an object can _declare_ dependencies for angular to inject when it is eventually constructed (think like a provided dependency in maven).

AFAIK, it's the only time you can have (or would want) an anonymous Controller though.

**Comment by bhill6** [comment]
Paul,

I don't have access to the repo you shared a link to, but in my case, I'm instantiating controllers via the ng-controller notation. I'm not using ngRoute, but I agree that using $inject is always a good idea.

**Comment by paulerickson** [comment]
Woops - I gave you access now, but I guess it doesn't help you anyway :/

**Comment by bhill6** [comment]
Thanks anyway! :+1:
